apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ci-nuxt
  name: ci-nuxt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ci-nuxt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ci-nuxt
    spec:
      containers:
      - image: harbor.ks.io:8443/ceresinventory/nuxt:8
        name: ci-nuxt
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: ci-nuxt