apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nuxt
  template:
    metadata:
      labels:
        name: nuxt
    spec:
      containers:
      - image: harbor.ks.io:8443/ceresinventory/nuxt:13
        name: nuxt-container
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nuxt-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    name: nuxt