apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: examplenode
  name: examplenode
spec:
  replicas: 3
  selector:
    matchLabels:
      app: examplenode
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: examplenode
    spec:
      containers:
      - image: neopubl/test:11
        name: examplenode
        resources: {}
status: {}
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: lb-service
#   labels:
#     app: lb-service
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 5000
#   selector:
#     app: examplenode
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-service
spec:
  type: ClusterIP
  ports:
  - port: 3030
    targetPort: 5000
  selector:
    app: examplenode