apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: go
  template:
    metadata:
      labels:
        name: go
    spec:
      containers:
      - image: harbor.ks.io:8443/ceresinventory/go:latest
        name: go-container
        ports:
        - containerPort: 3031
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3031
  selector:
    name: go